services:
  bot:
    build: .
    container_name: nestjs-telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - bot-network
    command: [ "node", "dist/main.js" ]

networks:
  bot-network:
    driver: bridge
